compat_sources=player_v26
minecraft_version_compat=~26.3
java_language_version=25

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loom_plugin=net.fabricmc.fabric-loom

# Other mods
fabric_version=0.161.0+26.3
modmenu_version=21.0.0
cloth_config_version=26.3.159
